  version: '3.1'
  services:
    adminer:
      image: adminer
      ports:
        - "8091:8080"
      restart: 'no'
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: nu
      ports:
        - "5432:5432"
      restart: 'no'
      volumes:
        - db_data:/var/lib/postgresql/data
  volumes:
    db_data: